import Head from "next/head";
import styles from "../styles/Home.module.css";
import NavBar from "./components/navBar";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <NavBar />
        <h1 className={styles.title}>
          Welcome to my <a href="https://nextjs.org">Next.js!</a> Lesson note
        </h1>

        <p className={styles.description}>
          This is HOME from <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="/about" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <h3>
          Check this course in{" "}
          <a
            href="https://nomadcoders.co/nextjs-fundamentals"
            target="_blank"
            rel="noopener noreferrer"
            style={{ color: "#ff971b" }}
          >
            NOMAD CODERS
          </a>
        </h3>
      </footer>
    </div>
  );
}
